### PR TITLE
Fix/pm 73 headers custom messages

### PR DESCRIPTION
**Pull request by RutgerVanBeek**
Closes PM-73

## Description

Custom messages in the March-iv repo were changed. An header was added. For the messages generated in the hardware-interface the time field of the header is filled. 
## Changes

At two points the time field of the header is filled.

### CODE REVIEW

**Comment by Olavhaasie** [comment]
PM-73

**Comment by Olavhaasie** [comment]
You should also add the header time stamp here

https://github.com/project-march/hardware-interface/blob/17757c1acc7e57fa1fe8302e05336f6fa357b053/march_hardware_state_controller/src/march_hardware_state_controller.cpp#L45-L52

**Comment by RutgerVanBeek** [comment]
> You should also add the header time stamp here
> 
> https://github.com/project-march/hardware-interface/blob/17757c1acc7e57fa1fe8302e05336f6fa357b053/march_hardware_state_controller/src/march_hardware_state_controller.cpp#L45-L52

The message published here is the standard message. This is thus not a custom mesage.

**Comment by Olavhaasie** [comment]
Okay we should also take a look at the usefulness of the `march_hardware_state_controller`

**Review by Olavhaasie — APPROVED** [review]

**Pull request merged**
