### PR TITLE
Change joint limits check to use hard limits instead of soft

### LINKED ISSUE #121: Refactor outsidelimits check to use joint_limits, not soft_limits on startup
As we always home on startup, the exoskeleton can also be withing it's hard position limits on startup.

I believe the `hard_limits_` handle was removed so it needs to be readded from the urdf.

### PR DESCRIPTION
**Pull request by Ishadijcks**
Closes #121 

Needs to be tested on the exoskeleton

### CODE REVIEW

**Comment by martijnvandermarel** [comment]
@Ishadijcks I believe the error that is described in issue #121 is thrown in the imotioncube::goToOperationEnabled method (https://github.com/project-march/hardware-interface/blob/develop/march_hardware/src/IMotionCube.cpp), not the outsideLimitsCheck method in the hardware interface. So I believe this PR doesn't fix the issue?

**Comment by Ishadijcks** [comment]
I'm not sure which check you mean, the one I see uses the encoder values, that should be correct?

**Comment by JitskedeVries** [comment]
> @Ishadijcks I believe the error that is described in issue #121 is thrown in the imotioncube::goToOperationEnabled method (https://github.com/project-march/hardware-interface/blob/develop/march_hardware/src/IMotionCube.cpp), not the outsideLimitsCheck method in the hardware interface. So I believe this PR doesn't fix the issue?

Plus I think we should still check whether we are inside the softlimits instead of the jointlimits before we can actuate. It is more safe.

**Comment by Ishadijcks** [comment]
That is the current behaviour.

**Comment by Ishadijcks** [comment]
@martijnvandermarel we can close this pr now right?

**Comment by martijnvandermarel** [comment]
> @martijnvandermarel we can close this pr now right?

Yes I suppose so.

**Comment by TimBuckers** [comment]
Delete this branch?

**Pull request closed without merging**
