### PR TITLE
Fix/voltage velocity reading calculation

### PR DESCRIPTION
**Pull request by Ciliaclaij**
## Description

Changed motor voltage reading to signed integer instead of unsigned integer. Also fixed faulty calculation of the velocity from the voltage. 

## Changes

* Changed motor voltage reading to signed integer instead of unsigned integer
* Fixed calculation of the velocity from voltage

### CODE REVIEW

**Review by RutgerVanBeek — DISMISSED** [review]
I would test during the software tests, whether using signed instead of unsigned fixes it perfectly or whether there is still a conversion missing.

**Review by Olavhaasie — COMMENTED** [review]
The changes look good. How are the results?

**Comment by Ciliaclaij** [comment]
I don't have the results yet :( Rutger has not been able yet to convert the logfile to a CSV, so I need to wait for that...

**Review by RutgerVanBeek — COMMENTED** [review]
Changes are fine, but as you said yourself there is an offset and scaling factor, so let's wait until it exactly does what we expect.

**Pull request closed without merging**
